export const categories = [
  { id: 1, title: "Pasta" },
  { id: 2, title: "Pizza" },
  { id: 3, title: "Dessert" },
  { id: 4, title: "Coffee" },
];

export const menu_list = [
  {
    id: 100,
    title: "Spaghetti bolognese",
    ingredients: `A hearty Italian favorite featuring al dente spaghetti topped with
a slow-simmered, rich meat sauce made with ground beef, tomatoes,
 onions, garlic, and aromatic herbs.
 Finished with Parmesan cheese and fresh basil (1,7)`,
    price: "15",
    image: "bolognese.jpg",
    catId: 1,
  },
  {
    id: 101,
    title: "Carbonara",
    ingredients: `c Roman dish featuring al dente pasta tossed with crispy pancetta,
 egg yolk, Pecorino Romano, and black pepper`,
    price: "15",
    image: "carbonara.jpeg",
    catId: 1,
  },
  {
    id: 102,
    title: "Beef lasagna",
    ingredients: `tta cheese, baked with a hearty tomato sauce and topped
with melted mozzarella and Parmesan`,
    price: "16.5",
    image: "lasagna.jpg",
    catId: 1,
  },
  {
    id: 103,
    title: "True mushroom risotto",
    ingredients: `amy Arborio rice slow-cooked to perfection with a blend of
 wild mushrooms, Parmesan cheese, and a touch of white wine.
Finished with aromatic truffle oil and fresh herbs for an indulgent,`,
    price: "17",
    image: "risotto.webp",
    catId: 1,
  },
  {
    id: 104,
    title: "Classic margherita",
    ingredients: `Fior Di latte, basil, evoo, sea salt flakes`,
    price: "15",
    image: "margherita.jpeg",
    catId: 2,
  },
  {
    id: 105,
    title: "Pepperoni",
    ingredients: `Fior Di latte, oregano`,
    price: "16",
    image: "pepperoni.jpeg",
    catId: 2,
  },
  {
    id: 106,
    title: "Piccante",
    ingredients: `Spicy salami, fior di latte, peppers and chili oil`,
    price: "17",
    image: "piccante.webp",
    catId: 2,
  },
  {
    id: 107,
    title: "Piccante",
    ingredients: `Cream base, bacon, parmigiana, garlic`,
    price: "18",
    image: "carbonara-pizza.jpg",
    catId: 2,
  },

  {
    id: 108,
    title: "Naughty nutella pancake",
    ingredients: `Naughty nutella pancake`,
    price: "8.5",
    image: "pancakes.jpg",
    catId: 3,
  },
  {
    id: 109,
    title: "Hazelnut ice-cream",
    ingredients: `Hazelnut ice-cream`,
    price: "7.5",
    image: "ice-cream.jpg",
    catId: 3,
  },
  {
    id: 110,
    title: "Tiramisu",
    ingredients: `Tiramisu`,
    price: "8.5",
    image: "tiramisu.jpg",
    catId: 3,
  },
  {
    id: 111,
    title: "Lemon meringue",
    ingredients: `Lemon meringue`,
    price: "9.5",
    image: "lemon.webp",
    catId: 3,
  },
  {
    id: 112,
    title: "Espresso",
    ingredients: `Espresso`,
    price: "3",
    image: "espresso.jpg",
    catId: 4,
  },
  {
    id: 113,
    title: "Cappuccino",
    ingredients: `Cappuccino`,
    price: "3.5",
    image: "cappuccino.webp",
    catId: 4,
  },
  {
    id: 114,
    title: "Freddo Espresso",
    ingredients: `Freddo Espresso`,
    price: "2.5",
    image: "freddo.jpg",
    catId: 4,
  },
  {
    id: 115,
    title: "Iced Dolce Tea Latte",
    ingredients: `Iced Dolce Tea Latte`,
    price: "3.5",
    image: "latte.webp",
    catId: 4,
  },
];
